### ISSUE TITLE
Environment variable doesn't get used in control panel

### ISSUE THREAD

**Issue by bartrylant** [thomasvantuycom/craft-cloudinary#1]
When using an .env variable for Cloud Name, it doesn't get replaced in the control panel for thumbnails, previews, etc.

Source from a thumbnail in the control panel:

`<img src="https://res.cloudinary.com/$CLOUDINARY_CLOUDNAME/image/upload/c_crop,g_center,h_22,w_34/q_auto/f_auto/v1/testwerk/cover-2019_06_23_ML_bezoekers_kinderen_label_boom.jpg?_a=BAAAROAI 34w, https://res.cloudinary.com/$CLOUDINARY_CLOUDNAME/image/upload/c_crop,g_center,h_45,w_68/q_auto/f_auto/v1/testwerk/cover-2019_06_23_ML_bezoekers_kinderen_label_boom.jpg?_a=BAAAROAI 68w">`

**Comment by thomasvantuycom** [comment]
Hi Bart,

Thank you for letting me know. This should now be fixed and released in version 1.0.1.
