### ISSUE TITLE
Clarification of README

### ISSUE THREAD

**Issue by owe** [thomasvantuycom/craft-cloudinary#16]
This is probably not a bug, but a request for clarification in README.

> Point it to the base URL of your website followed by /actions/cloudinary/notifications/process?volume={VOLUME_ID}. Remember to replace {VOLUME_ID} with the relevant asset volume ID.

As far as I understand the volume Id is not something that is exposed anywhere, although the volume does have an Id. Only the handle is exposed, however replacing {VOLUME_ID} with the handle doesn't seem to work.

**Comment by thomasvantuycom** [comment]
You can find a volume's ID by going to its settings in the admin panel. The ID will be displayed in the URL as follows: `admin/settings/assets/volumes/{VOLUME_ID}`. I agree that this could use some clarification in the README.
