### ISSUE TITLE
CP Thumbnail Transforms w/h dimensions reversed?

### ISSUE THREAD

**Issue by robinbeatty** [thomasvantuycom/craft-cloudinary#2]
Only a few minutes into using your plugin, but expecting to use this as a long term solution for Cloudinary integration – I noticed that the thumbnails in Craft CP asset views are wrongly cropped: it looks like somewhere in the pipeline the width/height dimensions are being reversed (width = height and height = width) and therefore the transformation that Cloudinary delivers appears eccentrically cropped in the center. 

E.g.

Original image (asset preview panel, correct)
<img width="359" alt="Screenshot 2023-11-14 at 13 53 44" src="https://github.com/thomasvantuycom/craft-cloudinary/assets/48855073/997ff6b5-7fdb-4a50-b3a4-25e68264d550">

Wrongly cropped image (Assets field / Assets picker thumbnail view)
<img width="185" alt="Screenshot 2023-11-14 at 13 53 53" src="https://github.com/thomasvantuycom/craft-cloudinary/assets/48855073/ee42437d-684d-496d-b631-43bf489df5c3">

Likewise with vertical images:

Original (asset edit modal):
<img width="1238" alt="Screenshot 2023-11-14 at 13 58 37" src="https://github.com/thomasvantuycom/craft-cloudinary/assets/48855073/4ca2eb80-79f6-4887-80b7-2eab9e52d3d0">

Wrongly cropped thumbnail:
<img width="337" alt="Screenshot 2023-11-14 at 13 58 49" src="https://github.com/thomasvantuycom/craft-cloudinary/assets/48855073/15430b0d-f567-44a8-9276-80e4364512bd">

Not sure where it's happening but looks to me like the width is being given the height's value and vice versa somewhere along the way...

Would be great to get a fix!
Many thanks, cheers for great plugin.

**Comment by thomasvantuycom** [comment]
Hi @robinbeatty,

Thank you for letting me know. There was an inconsistency in the crop behaviour between Craft CMS and Cloudinary. This should now be fixed and released in version 1.2.1.
