### ISSUE TITLE
Undefined array key "folder"

### ISSUE THREAD

**Issue by robinbeatty** [thomasvantuycom/craft-cloudinary#3]
Hey, since upgrade to 1.2.1 assets won't index via `php craft index-assets <volume name>` and throws exception 'Undefined Array Key "folder"' at CloudinaryFs.php:72

Pretty sure this was fine in 1.2.0. Could you take a look?
Many thanks!

**Comment by robinbeatty** [comment]
My bad – this is a problem with my Cloudinary config – not the plugin (tested with alternative cloudinary account and indexing works fine).

FYI the difference is something to do with the account's tier... might be good to detect the response to and render something useful to the user for this case?

**Comment by thomasvantuycom** [comment]
I'm curious whether the issue is related to [dynamic folder mode](https://cloudinary.com/documentation/dynamic_folders#folder_param). Can you please verify whether the problem is resolved by updating line 65 in `src/fs/CloudinaryFs.php` as follows?
```php
'dirname' => $asset['asset_folder'] ?? $asset['folder'],
```

**Comment by robinbeatty** [comment]
Yes that solves it :) Fantastic. In the meantime I had been comparing the settings of each account and indeed 'Dynamic Folders' is the only setting that's different.

**Comment by thomasvantuycom** [comment]
Alright, great. Don't hesitate to keep sharing bug reports. Despite the care taken, it's likely that more issues will appear with the plugin.

**Comment by robinbeatty** [comment]
Ok thanks. ... think there must be another thing regarding this to update in the plugin. Yes the assets will index having updated to `$asset['asset_folder'] ?? $asset['folder']` but in the get request for the Cloudinary transform is now returning 404. Does something need configuring there too?

**Comment by thomasvantuycom** [comment]
Is the folder where the asset is stored different from the path segment in the delivery url (`Accommodation/Alyeska%20Resort`), in Craft or in the Cloudinary media library dashboard?

**Comment by robinbeatty** [comment]
Ok, think this is being caused by assets that were previously deleted from cloudinary linging in a cache. After clearing Craft asset index caches, deleting the filesystem and volume and re-adding them I can now index the assets – strangely the assets that get indexed (as displayed in the console feedback) are those of the deleted cloudinary assets, but when I view /admin/assets list view I only see the correct assets as I would expect to see, and the image transform urls are correct, rendering the correct thumbnail. Not sure whether this is a stale cache issue on Cloudinary or Craft. The only unexpected behaviour here is the asset indexing, which appears to index more assets than are present in the cloudinary library.

**Comment by robinbeatty** [comment]
Sorry, no actually – this is only now indexing files at 'root level' in Cloudinary. If there are subfolders in Cloudinary, the folders arrive as Craft asset folders, but they do not contain any images.

**Comment by robinbeatty** [comment]
Just to confirm that, having heard back from Cloudinary support, Dynamic Folders is enabled for this account, whereas the other account it's not enabled.

**Comment by thomasvantuycom** [comment]
Having access to your setup and Cloudinary account would be really helpful, since I don't have an account with dynamic folders. I can have a look at it tomorrow.

**Comment by thomasvantuycom** [comment]
The issue has been addressed and incorporated into version 1.3.0, which is now available. As dynamic folders mode is a recent addition to the Cloudinary API, I'm labeling this as an enhancement.

**Comment by robinbeatty** [comment]
Thanks for the update. All works as expected – There's one thing I noticed that would be useful – when assets get deleted from the remote source they correctly get removed when craft re-indexes the volume. However, if they were in a subfolder, the subfolders in craft remain (as empty folders). Is there a way of automatically deleting the folders in craft if they don't exist in cloudinary?

**Comment by thomasvantuycom** [comment]
I believe that's standard Craft behaviour, and that that's why the "List empty folders" option exists in the asset indexing utility.

![Screenshot 2023-11-19 at 21-51-10 Asset Indexes - Craft CMS](https://github.com/thomasvantuycom/craft-cloudinary/assets/107400578/cd526de6-3567-4cdb-80fd-90b17c601e45)
