### ISSUE TITLE
Check if asset exists in cloudinary before upload?

### ISSUE THREAD

**Issue by robinbeatty** [thomasvantuycom/craft-cloudinary#4]
Hi Thomas, on before upload to cloudinary how easy would it be to implement a quick query to see if the asset already exists (matched by filename/bytes) and if so, insert the existing asset into the index rather than a duplicate? (to match the behaviour of craft's native assets fs)? This would be ideal for our use case.

**Comment by thomasvantuycom** [comment]
Hi Robin,

I'm not quite sure what you mean. When I re-upload the identical asset, Craft identifies it and suggests replacing the current one, both for the Cloudinary filesystem and the native local filesystem. Are you referring to a different scenario?

https://github.com/thomasvantuycom/craft-cloudinary/assets/107400578/e677eb94-a539-4f93-b7f4-daebac165ed7

**Comment by thomasvantuycom** [comment]
I'll explore [webhooks](https://cloudinary.com/documentation/notifications) as they are likely more appropriate for implementing this type of two-way synchronization.

**Comment by thomasvantuycom** [comment]
Just a quick update: I haven't managed to make it work yet.  I'm curious about your choice to use the Cloudinary upload widget. Wouldn't the issue be resolved by allowing Craft to manage the frontend user's uploads?

**Comment by robinbeatty** [comment]
The reason is because we need the full Cloudinary media browser experience – navigate folders, search, AI generated tags on upload etc etc. It would be a huge project to roll our own on top of Craft's GraphQL api. But we do need the assets uploaded like this to be immediately available as Craft assets. Another solution could be to be able to ask Craft to index one Cloudinary asset by filename.. do you know if that is possible?

**Comment by thomasvantuycom** [comment]
Alright, so it is possible to index a single asset. Here's how: 
```php
$volume = Craft::$app->getVolumes()->getVolumeByHandle('cloudinary');
$assetIndexer = Craft::$app->getAssetIndexer();
$session = $assetIndexer->createIndexingSession([$volume], false);
$assetIndexer->indexFile($volume, 'path/to/test.jpg', $session->id);
$assetIndexer->stopIndexingSession($session);
```
Here's the suggested workflow: first, upload the asset to Cloudinary using the upload widget. Next, index the asset in Craft by utilizing the file path from the returned data, which includes the folder and public ID. Finally, query Craft for the asset's ID.

**Comment by robinbeatty** [comment]
Thanks for the tip! That looks like a great solution. Will create a controller to wrap this all together. Many thanks!
